# Generated by Django 3.1.2 on 2020-10-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=100)),
                ('position_name', models.CharField(max_length=100)),
                ('hire_date', models.DateField()),
                ('fire_date', models.DateField(null=True)),
                ('salary', models.IntegerField()),
                ('fraction', models.IntegerField()),
                ('base', models.IntegerField()),
                ('advance', models.IntegerField()),
                ('by_hours', models.BooleanField()),
            ],
        ),
    ]
