# Generated by Django 3.1.2 on 2020-10-07 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Occupation',
        ),
    ]
