# Generated by Django 3.1.2 on 2020-10-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0003_auto_20201009_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='fire_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='hire_date',
            field=models.DateField(),
        ),
    ]
