# Generated by Django 3.1.2 on 2020-10-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0004_auto_20201009_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='fire_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='hire_date',
            field=models.CharField(max_length=100),
        ),
    ]
