# Generated by Django 3.1.2 on 2020-10-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0006_auto_20201009_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='fire_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
