# Generated by Django 3.1.2 on 2020-10-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0007_auto_20201011_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='fire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
